# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# Commands and Apps to be executed at launch

# Restore the last image selected independently for each swww output.
exec-once = sleep 1 && swww restore

